apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-devops-proj3
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-09e3fea6d28474380 }
      us-east-1b: { id: subnet-0496bf8a0ba413202 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
